# Generated by Django 5.2.7 on 2025-10-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'ordering': ['-created_at'], 'verbose_name': '2. Billing Address', 'verbose_name_plural': '2. Billing Addresses'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': '1. Customer', 'verbose_name_plural': '1. Customer List'},
        ),
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'ordering': ['-created_at'], 'verbose_name': '3. Delivery Address', 'verbose_name_plural': '3. Delivery Addresses'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at'], 'verbose_name': '6. OTP', 'verbose_name_plural': '6. OTPs'},
        ),
        migrations.AlterModelOptions(
            name='tradedocument',
            options={'ordering': ['-created_at'], 'verbose_name': '5. Trade Document', 'verbose_name_plural': '5. Trade Documents'},
        ),
        migrations.AlterModelOptions(
            name='tradeinformation',
            options={'verbose_name': '4. Trade Information', 'verbose_name_plural': '4. Trade Information'},
        ),
    ]
