# Generated by Django 5.2.7 on 2025-11-12 18:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Short Description'),
        ),
    ]
